#!/usr/bin/env python3
"""Author WebVTT captions for every narrated video, from the build data.

WHY THIS EXISTS. Nine videos ship on this site, every one of them narrated —
the audio track was measured and carries speech in all nine — and not one had a
<track>. That is WCAG 2.1 SC 1.2.2 Captions (Prerecorded) at LEVEL A, on a site
that publishes an accessibility argument and whose author documents his own
accessibility miss as a credential.

NOTHING HERE IS TRANSCRIBED OR INVENTED. The narration was synthesised from his
own scripts, and each build kept its receipts:
  durations.json        segment order and each segment's length in seconds
  seg-NN-bounds.json    per-SENTENCE offset_ms and duration_ms inside a segment
Cue text is the sentence; cue timing is that sentence's own measured bounds.

THE OFFSET IS ZERO, AND THAT IS MEASURED, NOT ASSUMED. Every video is ~1.7s
longer than its narration, which could have been a lead-in (shifting every cue)
or a tail (shifting nothing). Decoding the audio with the Web Audio API and
scanning for the first sample above a silence floor put the first sound at
0.143s (o2), 0.129s (adtech) and 0.150s (the walkthrough) — so audio and video
start together and the ~1.7s is a tail. Guessing here would have put every
caption 1.7 seconds out.

THE ONLY EDIT TO THE WORDS is un-spacing the capitals the TTS needed: the script
says "P T C" so the voice spells it, but a caption reader wants "PTC". Runs of
single capitals are joined; nothing else is touched. Spoken numbers stay as
written — "four million" is good captioning and rewriting 60 of them to digits
would be editorial, not mechanical.
"""
import json, os, re, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'portfolio-sources', 'video')
OUT  = os.path.join(ROOT, 'assets', 'video')

# build folder -> the shipped video it narrates
BUILDS = {
    'build':              'process-walkthrough',
    'build-adtech':       'case-adtech',
    'build-fintech':      'case-fintech',
    'build-o2':           'case-o2',
    'build-orgos':        'case-orgos',
    'build-planit':       'case-planit',
    'build-ptc':          'case-ptc',
    'build-vc-diligence': 'case-vc-diligence',
}

CAPS = re.compile(r'\b((?:[A-Z] ){1,6}[A-Z])\b')

# A LOWERCASE LETTER LED INTO THE RUN cannot be resolved mechanically: in
# "i O S" the i belongs to the acronym and in "a D S P" it is the article.
# The general rule gets the second one right on its own, so only the genuine
# lowercase-led names are listed, and the list is short because the scripts are.
LOWER_LED = {'i O S': 'iOS'}


def unspace(text):
    """"P T C" -> "PTC". The spacing is a pronunciation instruction, not spelling."""
    for a, b in LOWER_LED.items():
        text = text.replace(a, b)
    return CAPS.sub(lambda m: m.group(1).replace(' ', ''), text)


def ts(seconds):
    seconds = max(0.0, seconds)
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    return '%02d:%02d:%06.3f' % (h, m, s)


def cues_for(build):
    d = os.path.join(SRC, build)
    meta = json.load(open(os.path.join(d, 'durations.json'), encoding='utf-8'))
    cues, at = [], 0.0
    for seg in meta['segments']:
        bpath = os.path.join(d, 'seg-%s-bounds.json' % seg['n'])
        if not os.path.exists(bpath):
            raise SystemExit('no bounds for %s seg %s — cannot time its cues' % (build, seg['n']))
        for c in json.load(open(bpath, encoding='utf-8')):
            start = at + c['offset_ms'] / 1000.0
            cues.append([start, start + c['duration_ms'] / 1000.0, unspace(c['text'].strip())])
        at += seg['seconds']
    # a cue must not outlast the next one's start — the bounds are per segment and
    # a sentence's measured duration can include trailing silence
    for i in range(len(cues) - 1):
        cues[i][1] = min(cues[i][1], cues[i + 1][0] - 0.001)
    return cues, meta['total']


def main():
    check = '--check' in sys.argv
    bad, wrote = [], 0
    for build, name in sorted(BUILDS.items()):
        cues, total = cues_for(build)
        body = ['WEBVTT', '',
                'NOTE Generated by tools/build-captions.py from',
                'NOTE portfolio-sources/video/%s/{durations,seg-NN-bounds}.json' % build,
                'NOTE Cue text is the narration script; timings are its measured bounds.', '']
        for i, (a, b, t) in enumerate(cues, 1):
            body += [str(i), '%s --> %s' % (ts(a), ts(b)), t, '']
        text = '\n'.join(body)
        path = os.path.join(OUT, name + '.vtt')
        have = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        drift = cues[-1][1] - total
        print('  %-22s %3d cues · last ends %7.3f · narration %7.3f (%+.3f)'
              % (name, len(cues), cues[-1][1], total, drift))
        if have != text:
            if check:
                bad.append(name)
            else:
                open(path, 'w', encoding='utf-8').write(text)
                wrote += 1
    print()
    if check and bad:
        print('STALE — %d caption file(s) differ from the build data: %s' % (len(bad), ', '.join(bad)))
        print('Result: STALE — run without --check.')
        return 1
    print('CANNOT SEE: whether the narration script matches what the voice actually said,')
    print('whether a cue is readable at its own length, or speaker changes and sound effects.')
    print('Result: clean — %s.' % ('every caption file matches the build data' if check
                                   else '%d file(s) written' % wrote))
    return 0


if __name__ == '__main__':
    sys.exit(main())
